language: clojure
before_install: echo $HOME
install:
- curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
- chmod +x linux-install-1.10.1.469.sh
- sudo ./linux-install-1.10.1.469.sh
- rm linux-install-1.10.1.469.sh
script: make build

deploy:
  provider: releases
  api_key:
    secure: xzmqk2h5bzgoZSfJY64rrAxTZ6C6mg4FC1B+a217c6uhK7VHbQM85B6y6GZN6MesW9FD5l+X3MFmEOX2vELGuUDL/8VUKaWEnDvSm1xx5AjUraMUtrz3grqfqz68eunu6FLC1uiyqWq5gvjL73xAYtNNdkqDzXfPxHWRLfjZIxHVL2piHHVK8749/pFojO/zLhBov8AwtdOKDk3zh+CSHNfhhzAiaoXYOVJRkR9WFUMbsgHzbslqWLaU0WQlWR9BscIDoLBARbzyz4JO+JUVI8r1s6/ojEtllUA7TlbWatsgaR4qVogiGpRXecB4PXIAJfIszFeNzWStQUu921nQ8CE7T0uPz9D1NzPp3igI2pDHBWZGDpExN/EJjoIiuT7zrU5/9Ca5UQggMe0iKQ6MjDWUYGdBeZste0SCSnJEi5b0jKaMTr1+lmZRN6OypPbTOJhqsqXsIEEoxkwfvyOLGr2MUxiWn80CqT2CypqMWCLzzh3VGmct1LWT26URbeIBQ9jOE5PyM2V4OBzm9hrEWeRxgHI5aL51WVNEvowQBLFi3XA6WFTCf5wJWO1j+lLMn9NnLAsg0H4M4XEhQdMWUpXVytTis0CgSOAHcVGr8tHE+1SICBOXvKP5xCJQryLSrueQWY0KkaiQT3hEVXAaMB1AjIRzmI48Q1x6mRMPHqA=
  file_glob: true
  file: 'target/*.jar'
  skip_cleanup: true
  on:
    tags: true
    repo: Aidbox/stresty
