apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stresty

resources:
- ns.yaml
- stresty.yaml
- ing.yaml

images:
  - name: stresty
    newName: aidbox/stresty
    newTag: ${VERSION}
